/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author claud
 */
public class datosFinalesPrueba extends javax.swing.JPanel {

    /**
     * Creates new form datosFinalesPrueba
     */
    public datosFinalesPrueba() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoAzulDerecho = new javax.swing.JPanel();
        TituloDatosPrueba = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        tituloRespondidasBien = new javax.swing.JLabel();
        respondidasBien = new javax.swing.JTextField();
        tituloRespondidasMal = new javax.swing.JLabel();
        respondidasMal = new javax.swing.JTextField();
        tituloResultadoFinal = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        totalPuntos = new javax.swing.JTextField();
        puntos = new javax.swing.JLabel();
        Siguiente = new javax.swing.JButton();
        datosEstudianteTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nombreApellidoTitulo = new javax.swing.JLabel();
        nombreApellido = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        identificacionTitulo = new javax.swing.JLabel();
        identificacion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        imagen = new javax.swing.JLabel();
        dichoProgramacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(228, 251, 251));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoAzulDerecho.setBackground(new java.awt.Color(15, 192, 255));
        FondoAzulDerecho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloDatosPrueba.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TituloDatosPrueba.setForeground(new java.awt.Color(0, 0, 0));
        TituloDatosPrueba.setText("Datos de la prueba");
        FondoAzulDerecho.add(TituloDatosPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));
        FondoAzulDerecho.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 190, 10));

        tituloRespondidasBien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloRespondidasBien.setForeground(new java.awt.Color(0, 0, 0));
        tituloRespondidasBien.setText("- Número de preguntas respondidas correctamente:");
        FondoAzulDerecho.add(tituloRespondidasBien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        respondidasBien.setEditable(false);
        respondidasBien.setBackground(new java.awt.Color(15, 192, 255));
        respondidasBien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        respondidasBien.setForeground(new java.awt.Color(0, 0, 0));
        respondidasBien.setText("jTextField2");
        respondidasBien.setBorder(null);
        FondoAzulDerecho.add(respondidasBien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        tituloRespondidasMal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tituloRespondidasMal.setForeground(new java.awt.Color(0, 0, 0));
        tituloRespondidasMal.setText("- Número de preguntas respondidas incorrectamente:");
        FondoAzulDerecho.add(tituloRespondidasMal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        respondidasMal.setEditable(false);
        respondidasMal.setBackground(new java.awt.Color(15, 192, 255));
        respondidasMal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        respondidasMal.setForeground(new java.awt.Color(0, 0, 0));
        respondidasMal.setText("jTextField4");
        respondidasMal.setBorder(null);
        FondoAzulDerecho.add(respondidasMal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        tituloResultadoFinal.setBackground(new java.awt.Color(15, 192, 255));
        tituloResultadoFinal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tituloResultadoFinal.setForeground(new java.awt.Color(0, 0, 0));
        tituloResultadoFinal.setText("Resultado final");
        FondoAzulDerecho.add(tituloResultadoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));
        FondoAzulDerecho.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 220, 10));

        totalPuntos.setEditable(false);
        totalPuntos.setBackground(new java.awt.Color(15, 192, 255));
        totalPuntos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalPuntos.setForeground(new java.awt.Color(0, 0, 0));
        totalPuntos.setText("jTextField2");
        totalPuntos.setBorder(null);
        FondoAzulDerecho.add(totalPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        puntos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        puntos.setForeground(new java.awt.Color(0, 0, 0));
        puntos.setText("Puntos");
        FondoAzulDerecho.add(puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        Siguiente.setBackground(new java.awt.Color(255, 204, 0));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(0, 0, 0));
        Siguiente.setText("Siguiente");
        Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        FondoAzulDerecho.add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 130, 50));

        add(FondoAzulDerecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 410, 520));

        datosEstudianteTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        datosEstudianteTitulo.setForeground(new java.awt.Color(0, 0, 0));
        datosEstudianteTitulo.setText("Datos del estudiante");
        add(datosEstudianteTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 230, 20));

        nombreApellidoTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nombreApellidoTitulo.setForeground(new java.awt.Color(0, 0, 0));
        nombreApellidoTitulo.setText("Nombre y apellido:");
        add(nombreApellidoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        nombreApellido.setEditable(false);
        nombreApellido.setBackground(new java.awt.Color(228, 251, 251));
        nombreApellido.setForeground(new java.awt.Color(0, 0, 0));
        nombreApellido.setBorder(null);
        nombreApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreApellidoActionPerformed(evt);
            }
        });
        add(nombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 400, 30));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 410, 10));

        identificacionTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        identificacionTitulo.setForeground(new java.awt.Color(0, 0, 0));
        identificacionTitulo.setText("Identificación:");
        add(identificacionTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        identificacion.setEditable(false);
        identificacion.setBackground(new java.awt.Color(228, 251, 251));
        identificacion.setForeground(new java.awt.Color(0, 0, 0));
        identificacion.setBorder(null);
        identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                identificacionActionPerformed(evt);
            }
        });
        add(identificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 400, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 410, 10));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/programacionImagen.png"))); // NOI18N
        add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, 140));

        dichoProgramacion.setBackground(new java.awt.Color(228, 251, 251));
        dichoProgramacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dichoProgramacion.setForeground(new java.awt.Color(0, 0, 0));
        dichoProgramacion.setText("\"Si puedes imaginarlo, puedes programarlo\"");
        add(dichoProgramacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 310, -1));

        jPanel1.setBackground(new java.awt.Color(228, 251, 251));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreApellidoActionPerformed

    private void identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_identificacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FondoAzulDerecho;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel TituloDatosPrueba;
    private javax.swing.JLabel datosEstudianteTitulo;
    private javax.swing.JLabel dichoProgramacion;
    private javax.swing.JTextField identificacion;
    private javax.swing.JLabel identificacionTitulo;
    private javax.swing.JLabel imagen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombreApellido;
    private javax.swing.JLabel nombreApellidoTitulo;
    private javax.swing.JLabel puntos;
    private javax.swing.JTextField respondidasBien;
    private javax.swing.JTextField respondidasMal;
    private javax.swing.JLabel tituloRespondidasBien;
    private javax.swing.JLabel tituloRespondidasMal;
    private javax.swing.JLabel tituloResultadoFinal;
    private javax.swing.JTextField totalPuntos;
    // End of variables declaration//GEN-END:variables
}
