/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Container;
import javax.swing.JOptionPane;
import modelos.Participante;
import modelos.Question;

/**
 *
 * @author claud
 */
public class PreguntaTrueOrFalseModelo extends javax.swing.JPanel {

    private Question[] preguntas;
    private int posicion;
    private Question preguntaActual;
    private Participante participante;
    private PrincipalView cronometro;
    
    /**
     * Creates new form pregunta1modelo
     * @param preguntas
     * @param posicion
     * @param participante
     * @param cronometro
     */
    public PreguntaTrueOrFalseModelo(Question[] preguntas, int posicion, Participante participante, PrincipalView cronometro) {
        initComponents();

        this.preguntas = preguntas;
        this.posicion = posicion;
        this.preguntaActual = preguntas[posicion];
        this.participante = participante;
        this.cronometro = cronometro;

        pregunta.setText("<html>" + preguntaActual.getPregunta() + "</html>");

        javax.swing.JRadioButton[] select = {verdadero, falso};

        if (preguntaActual.getRespuestasDelUsuario().length > 0) {
            int index = preguntaActual.getRespuestasDelUsuario()[0];
            select[index].setSelected(true);
        }

        if (posicion == 0) {
            btnAtras.setVisible(false);
        } else {
            btnCancelarPrueba.setVisible(false);
        }

        if (posicion == preguntas.length - 1) {
            btnSiguiente.setVisible(false);
        } else {
            btnFinalizarPrueba.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelDeBotonesIzquierdos = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnCancelarPrueba = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contenedor = new javax.swing.JPanel();
        contenedorPreguntas = new javax.swing.JPanel();
        pregunta = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        panelOpciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        verdadero = new javax.swing.JRadioButton();
        falso = new javax.swing.JRadioButton();
        panelDeBotonesDerecho = new javax.swing.JPanel();
        btnSiguiente = new javax.swing.JButton();
        btnFinalizarPrueba = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 251, 251));

        panelDeBotonesIzquierdos.setBackground(new java.awt.Color(228, 251, 251));
        panelDeBotonesIzquierdos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtras.setBackground(new java.awt.Color(15, 192, 255));
        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        panelDeBotonesIzquierdos.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 50));

        btnCancelarPrueba.setBackground(new java.awt.Color(15, 192, 255));
        btnCancelarPrueba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelarPrueba.setText("Cancelar Prueba");
        btnCancelarPrueba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPruebaActionPerformed(evt);
            }
        });
        panelDeBotonesIzquierdos.add(btnCancelarPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("* Verdadero o Falso");
        jLabel1.setToolTipText("");

        contenedor.setBackground(new java.awt.Color(204, 255, 255));
        contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contenedor.setPreferredSize(new java.awt.Dimension(830, 830));
        contenedor.setLayout(new javax.swing.BoxLayout(contenedor, javax.swing.BoxLayout.Y_AXIS));

        contenedorPreguntas.setBackground(new java.awt.Color(204, 255, 255));
        contenedorPreguntas.setPreferredSize(new java.awt.Dimension(828, 346));

        pregunta.setBackground(new java.awt.Color(204, 255, 255));
        pregunta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pregunta.setPreferredSize(new java.awt.Dimension(100, 100));

        jScrollPane6.setBorder(null);
        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        panelOpciones.setBackground(new java.awt.Color(204, 255, 255));
        panelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        panelOpciones.setLayout(new javax.swing.BoxLayout(panelOpciones, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        verdadero.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(verdadero);
        verdadero.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        verdadero.setText("Verdadero");
        verdadero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verdadero.setMargin(new java.awt.Insets(10, 10, 10, 10));
        verdadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdaderoActionPerformed(evt);
            }
        });

        falso.setBackground(new java.awt.Color(204, 255, 255));
        buttonGroup1.add(falso);
        falso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        falso.setText("Falso");
        falso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        falso.setMargin(new java.awt.Insets(10, 10, 10, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(verdadero)
                        .addComponent(falso))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(verdadero)
                    .addGap(0, 0, 0)
                    .addComponent(falso)
                    .addGap(0, 160, Short.MAX_VALUE)))
        );

        panelOpciones.add(jPanel1);

        jScrollPane6.setViewportView(panelOpciones);

        javax.swing.GroupLayout contenedorPreguntasLayout = new javax.swing.GroupLayout(contenedorPreguntas);
        contenedorPreguntas.setLayout(contenedorPreguntasLayout);
        contenedorPreguntasLayout.setHorizontalGroup(
            contenedorPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(contenedorPreguntasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        contenedorPreguntasLayout.setVerticalGroup(
            contenedorPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorPreguntasLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contenedor.add(contenedorPreguntas);

        panelDeBotonesDerecho.setBackground(new java.awt.Color(228, 251, 251));
        panelDeBotonesDerecho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguiente.setBackground(new java.awt.Color(15, 192, 255));
        btnSiguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        panelDeBotonesDerecho.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 110, 50));

        btnFinalizarPrueba.setBackground(new java.awt.Color(15, 192, 255));
        btnFinalizarPrueba.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFinalizarPrueba.setText("Finalizar Prueba");
        btnFinalizarPrueba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinalizarPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPruebaActionPerformed(evt);
            }
        });
        panelDeBotonesDerecho.add(btnFinalizarPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(panelDeBotonesIzquierdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDeBotonesDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelDeBotonesIzquierdos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDeBotonesDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPruebaActionPerformed
        ShowAlert alerta = new ShowAlert("Advertencia", "¿Seguro que quieres cancelar la prueba?, perderas todo el progreso que llevas",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (alerta.getRespuesta() == 0) {
            Container padre = this.getParent();

            SeleccionarLenguaje lenguaje = new SeleccionarLenguaje(this.participante, this.cronometro);
            lenguaje.setSize(880, 470);
            lenguaje.setVisible(true);

            padre.removeAll();
            padre.add(lenguaje);
            padre.revalidate();
            padre.repaint();
        }
    }//GEN-LAST:event_btnCancelarPruebaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (this.posicion == 0) {
            return;
        }

        if (verdadero.isSelected()) {
            int res[] = {0};
            this.preguntas[posicion].setRespuestasDelUsuario(res);
        }

        if (falso.isSelected()) {
            int res[] = {1};
            this.preguntas[posicion].setRespuestasDelUsuario(res);
        }

        Question[] preguntasPrueba = this.preguntas;
        Question nuevaPregunta = preguntasPrueba[this.posicion - 1];

        if (nuevaPregunta.getPosiblesRespuestas().length == 1) {
            PreguntaTextoModelo pregunta = new PreguntaTextoModelo(preguntasPrueba, this.posicion - 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getPosiblesRespuestas().length == 2) {
            PreguntaTrueOrFalseModelo pregunta = new PreguntaTrueOrFalseModelo(preguntasPrueba, this.posicion - 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getRespuestasCorrectas().length == 1) {
            Pregunta1RespuestaModelo pregunta = new Pregunta1RespuestaModelo(preguntasPrueba, this.posicion - 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getRespuestasCorrectas().length == 2) {
            Pregunta2RespuestasModelo pregunta = new Pregunta2RespuestasModelo(preguntasPrueba, this.posicion - 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getRespuestasCorrectas().length == 3) {
            Pregunta3RespuestasModelo pregunta = new Pregunta3RespuestasModelo(preguntasPrueba, this.posicion - 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else {
            ShowAlert alerta = new ShowAlert("Error, tipo de pregunta no valida", "Tipo de pregunta no valida", JOptionPane.ERROR_MESSAGE);
            System.out.println(nuevaPregunta);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void verdaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdaderoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verdaderoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        if (this.posicion == 24) {
            return;
        }

        if (verdadero.isSelected()) {
            int res[] = {0};
            this.preguntas[posicion].setRespuestasDelUsuario(res);
        }

        if (falso.isSelected()) {
            int res[] = {1};
            this.preguntas[posicion].setRespuestasDelUsuario(res);
        }

        Question[] preguntasPrueba = this.preguntas;
        Question nuevaPregunta = preguntasPrueba[this.posicion + 1];

        if (nuevaPregunta.getPosiblesRespuestas().length == 1) {
            PreguntaTextoModelo pregunta = new PreguntaTextoModelo(preguntasPrueba, this.posicion + 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getPosiblesRespuestas().length == 2) {
            PreguntaTrueOrFalseModelo pregunta = new PreguntaTrueOrFalseModelo(preguntasPrueba, this.posicion + 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getRespuestasCorrectas().length == 1) {
            Pregunta1RespuestaModelo pregunta = new Pregunta1RespuestaModelo(preguntasPrueba, this.posicion + 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getRespuestasCorrectas().length == 2) {
            Pregunta2RespuestasModelo pregunta = new Pregunta2RespuestasModelo(preguntasPrueba, this.posicion + 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else if (nuevaPregunta.getRespuestasCorrectas().length == 3) {
            Pregunta3RespuestasModelo pregunta = new Pregunta3RespuestasModelo(preguntasPrueba, this.posicion + 1, this.participante, this.cronometro);
            pregunta.setSize(880, 470);
            pregunta.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(pregunta);
            padre.revalidate();
            padre.repaint();
        } else {
            ShowAlert alerta = new ShowAlert("Error, tipo de pregunta no valida", "Tipo de pregunta no valida", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnFinalizarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPruebaActionPerformed
        ShowAlert alerta = new ShowAlert("Terminar Prueba", "¿Estas seguro de querer terminar la prueba?",
                JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        int respuesta = alerta.getRespuesta();
        
        if(respuesta == 0){
            Respuestas resultados = new Respuestas(this.preguntas, 0, this.participante, this.cronometro);
            resultados.setSize(880, 470);
            resultados.setVisible(true);

            Container padre = this.getParent();

            padre.removeAll();
            padre.add(resultados);
            padre.revalidate();
            padre.repaint();
        }
    }//GEN-LAST:event_btnFinalizarPruebaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCancelarPrueba;
    private javax.swing.JButton btnFinalizarPrueba;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel contenedor;
    private javax.swing.JPanel contenedorPreguntas;
    private javax.swing.JRadioButton falso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel panelDeBotonesDerecho;
    private javax.swing.JPanel panelDeBotonesIzquierdos;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JLabel pregunta;
    private javax.swing.JRadioButton verdadero;
    // End of variables declaration//GEN-END:variables
}
