/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author claud
 */
public class totalpreguntas1 extends javax.swing.JPanel {

    /**
     * Creates new form totalpreguntas1
     */
    public totalpreguntas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Siguiente = new javax.swing.JButton();
        pregunta1 = new javax.swing.JLabel();
        pregunta2 = new javax.swing.JLabel();
        pregunta3 = new javax.swing.JLabel();
        pregunta4 = new javax.swing.JLabel();
        pregunta5 = new javax.swing.JLabel();
        respuesta1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        respuesta2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();
        respuesta3 = new javax.swing.JScrollPane();
        textArea3 = new javax.swing.JTextArea();
        respuesta4 = new javax.swing.JScrollPane();
        textArea4 = new javax.swing.JTextArea();
        respuesta5 = new javax.swing.JScrollPane();
        textArea5 = new javax.swing.JTextArea();
        tituloInterfaz = new javax.swing.JLabel();

        setBackground(new java.awt.Color(228, 251, 251));

        jPanel3.setBackground(new java.awt.Color(228, 251, 251));

        Siguiente.setBackground(new java.awt.Color(255, 204, 0));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(0, 0, 0));
        Siguiente.setText("Siguiente");
        Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        pregunta1.setBackground(new java.awt.Color(228, 251, 251));
        pregunta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta1.setForeground(new java.awt.Color(0, 0, 0));
        pregunta1.setText("Pregunta #1 -----------------------------------");

        pregunta2.setBackground(new java.awt.Color(228, 251, 251));
        pregunta2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta2.setForeground(new java.awt.Color(0, 0, 0));
        pregunta2.setText("Pregunta #2 -----------------------------------");

        pregunta3.setBackground(new java.awt.Color(228, 251, 251));
        pregunta3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta3.setForeground(new java.awt.Color(0, 0, 0));
        pregunta3.setText("Pregunta #3 -----------------------------------");

        pregunta4.setBackground(new java.awt.Color(228, 251, 251));
        pregunta4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta4.setForeground(new java.awt.Color(0, 0, 0));
        pregunta4.setText("Pregunta #4 -----------------------------------");

        pregunta5.setBackground(new java.awt.Color(228, 251, 251));
        pregunta5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta5.setForeground(new java.awt.Color(0, 0, 0));
        pregunta5.setText("Pregunta #5 -----------------------------------");

        textArea1.setBackground(new java.awt.Color(228, 251, 251));
        textArea1.setColumns(20);
        textArea1.setForeground(new java.awt.Color(0, 0, 0));
        textArea1.setLineWrap(true);
        textArea1.setRows(5);
        textArea1.setWrapStyleWord(true);
        textArea1.setBorder(null);
        respuesta1.setViewportView(textArea1);

        textArea2.setBackground(new java.awt.Color(228, 251, 251));
        textArea2.setColumns(20);
        textArea2.setForeground(new java.awt.Color(0, 0, 0));
        textArea2.setLineWrap(true);
        textArea2.setRows(5);
        textArea2.setWrapStyleWord(true);
        textArea2.setBorder(null);
        respuesta2.setViewportView(textArea2);

        textArea3.setBackground(new java.awt.Color(228, 251, 251));
        textArea3.setColumns(20);
        textArea3.setForeground(new java.awt.Color(0, 0, 0));
        textArea3.setLineWrap(true);
        textArea3.setRows(5);
        textArea3.setWrapStyleWord(true);
        textArea3.setBorder(null);
        respuesta3.setViewportView(textArea3);

        textArea4.setBackground(new java.awt.Color(228, 251, 251));
        textArea4.setColumns(20);
        textArea4.setForeground(new java.awt.Color(0, 0, 0));
        textArea4.setLineWrap(true);
        textArea4.setRows(5);
        textArea4.setWrapStyleWord(true);
        textArea4.setBorder(null);
        respuesta4.setViewportView(textArea4);

        textArea5.setBackground(new java.awt.Color(228, 251, 251));
        textArea5.setColumns(20);
        textArea5.setForeground(new java.awt.Color(0, 0, 0));
        textArea5.setLineWrap(true);
        textArea5.setRows(5);
        textArea5.setWrapStyleWord(true);
        textArea5.setBorder(null);
        respuesta5.setViewportView(textArea5);

        tituloInterfaz.setBackground(new java.awt.Color(228, 251, 251));
        tituloInterfaz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tituloInterfaz.setForeground(new java.awt.Color(0, 0, 0));
        tituloInterfaz.setText("Preguntas presentadas en la prueba");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pregunta5, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(tituloInterfaz)
                                .addGap(216, 216, 216))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(pregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(364, 364, 364))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloInterfaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pregunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pregunta5)
                .addGap(18, 18, 18)
                .addComponent(respuesta5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Siguiente;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pregunta1;
    private javax.swing.JLabel pregunta2;
    private javax.swing.JLabel pregunta3;
    private javax.swing.JLabel pregunta4;
    private javax.swing.JLabel pregunta5;
    private javax.swing.JScrollPane respuesta1;
    private javax.swing.JScrollPane respuesta2;
    private javax.swing.JScrollPane respuesta3;
    private javax.swing.JScrollPane respuesta4;
    private javax.swing.JScrollPane respuesta5;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextArea textArea2;
    private javax.swing.JTextArea textArea3;
    private javax.swing.JTextArea textArea4;
    private javax.swing.JTextArea textArea5;
    private javax.swing.JLabel tituloInterfaz;
    // End of variables declaration//GEN-END:variables
}
