/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author claud
 */
public class totalPreguntas2 extends javax.swing.JPanel {

    /**
     * Creates new form totalPreguntas2
     */
    public totalPreguntas2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Siguiente = new javax.swing.JButton();
        pregunta6 = new javax.swing.JLabel();
        pregunta7 = new javax.swing.JLabel();
        pregunta8 = new javax.swing.JLabel();
        pregunta9 = new javax.swing.JLabel();
        pregunta10 = new javax.swing.JLabel();
        respuesta6 = new javax.swing.JScrollPane();
        textArea6 = new javax.swing.JTextArea();
        respuesta7 = new javax.swing.JScrollPane();
        textArea7 = new javax.swing.JTextArea();
        respuesta8 = new javax.swing.JScrollPane();
        textArea8 = new javax.swing.JTextArea();
        respuesta9 = new javax.swing.JScrollPane();
        textArea9 = new javax.swing.JTextArea();
        respuesta10 = new javax.swing.JScrollPane();
        textArea10 = new javax.swing.JTextArea();
        tituloInterfaz = new javax.swing.JLabel();

        setBackground(new java.awt.Color(228, 251, 251));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 47, 470, 13));

        Siguiente.setBackground(new java.awt.Color(255, 204, 0));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(0, 0, 0));
        Siguiente.setText("Siguiente");
        Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 440, 130, 40));

        pregunta6.setBackground(new java.awt.Color(228, 251, 251));
        pregunta6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta6.setForeground(new java.awt.Color(0, 0, 0));
        pregunta6.setText("Pregunta #6 -----------------------------------");
        add(pregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, 830, -1));

        pregunta7.setBackground(new java.awt.Color(228, 251, 251));
        pregunta7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta7.setForeground(new java.awt.Color(0, 0, 0));
        pregunta7.setText("Pregunta #7 -----------------------------------");
        add(pregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 141, 830, -1));

        pregunta8.setBackground(new java.awt.Color(228, 251, 251));
        pregunta8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta8.setForeground(new java.awt.Color(0, 0, 0));
        pregunta8.setText("Pregunta #8 -----------------------------------");
        add(pregunta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, 830, -1));

        pregunta9.setBackground(new java.awt.Color(228, 251, 251));
        pregunta9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta9.setForeground(new java.awt.Color(0, 0, 0));
        pregunta9.setText("Pregunta #9 -----------------------------------");
        add(pregunta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 285, 830, 20));

        pregunta10.setBackground(new java.awt.Color(228, 251, 251));
        pregunta10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta10.setForeground(new java.awt.Color(0, 0, 0));
        pregunta10.setText("Pregunta #10 -----------------------------------");
        add(pregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 359, 830, -1));

        textArea6.setBackground(new java.awt.Color(228, 251, 251));
        textArea6.setColumns(20);
        textArea6.setForeground(new java.awt.Color(0, 0, 0));
        textArea6.setLineWrap(true);
        textArea6.setRows(5);
        textArea6.setWrapStyleWord(true);
        textArea6.setBorder(null);
        respuesta6.setViewportView(textArea6);

        add(respuesta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, 840, 30));

        textArea7.setBackground(new java.awt.Color(228, 251, 251));
        textArea7.setColumns(20);
        textArea7.setForeground(new java.awt.Color(0, 0, 0));
        textArea7.setLineWrap(true);
        textArea7.setRows(5);
        textArea7.setWrapStyleWord(true);
        textArea7.setBorder(null);
        respuesta7.setViewportView(textArea7);

        add(respuesta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 168, 840, 30));

        textArea8.setBackground(new java.awt.Color(228, 251, 251));
        textArea8.setColumns(20);
        textArea8.setForeground(new java.awt.Color(0, 0, 0));
        textArea8.setLineWrap(true);
        textArea8.setRows(5);
        textArea8.setWrapStyleWord(true);
        textArea8.setBorder(null);
        respuesta8.setViewportView(textArea8);

        add(respuesta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 243, 840, 30));

        textArea9.setBackground(new java.awt.Color(228, 251, 251));
        textArea9.setColumns(20);
        textArea9.setForeground(new java.awt.Color(0, 0, 0));
        textArea9.setLineWrap(true);
        textArea9.setRows(5);
        textArea9.setWrapStyleWord(true);
        textArea9.setBorder(null);
        respuesta9.setViewportView(textArea9);

        add(respuesta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 317, 840, 30));

        textArea10.setBackground(new java.awt.Color(228, 251, 251));
        textArea10.setColumns(20);
        textArea10.setForeground(new java.awt.Color(0, 0, 0));
        textArea10.setLineWrap(true);
        textArea10.setRows(5);
        textArea10.setWrapStyleWord(true);
        textArea10.setBorder(null);
        respuesta10.setViewportView(textArea10);

        add(respuesta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 392, 840, 30));

        tituloInterfaz.setBackground(new java.awt.Color(228, 251, 251));
        tituloInterfaz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tituloInterfaz.setForeground(new java.awt.Color(0, 0, 0));
        tituloInterfaz.setText("Preguntas presentadas en la prueba");
        add(tituloInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 12, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Siguiente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pregunta10;
    private javax.swing.JLabel pregunta6;
    private javax.swing.JLabel pregunta7;
    private javax.swing.JLabel pregunta8;
    private javax.swing.JLabel pregunta9;
    private javax.swing.JScrollPane respuesta10;
    private javax.swing.JScrollPane respuesta6;
    private javax.swing.JScrollPane respuesta7;
    private javax.swing.JScrollPane respuesta8;
    private javax.swing.JScrollPane respuesta9;
    private javax.swing.JTextArea textArea10;
    private javax.swing.JTextArea textArea6;
    private javax.swing.JTextArea textArea7;
    private javax.swing.JTextArea textArea8;
    private javax.swing.JTextArea textArea9;
    private javax.swing.JLabel tituloInterfaz;
    // End of variables declaration//GEN-END:variables
}
