/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author claud
 */
public class totalPreguntas3 extends javax.swing.JPanel {

    /**
     * Creates new form totalPreguntas3
     */
    public totalPreguntas3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Siguiente = new javax.swing.JButton();
        pregunta11 = new javax.swing.JLabel();
        pregunta12 = new javax.swing.JLabel();
        pregunta13 = new javax.swing.JLabel();
        pregunta14 = new javax.swing.JLabel();
        pregunta15 = new javax.swing.JLabel();
        respuesta11 = new javax.swing.JScrollPane();
        textArea11 = new javax.swing.JTextArea();
        respuesta12 = new javax.swing.JScrollPane();
        textArea12 = new javax.swing.JTextArea();
        respuesta13 = new javax.swing.JScrollPane();
        textArea13 = new javax.swing.JTextArea();
        respuesta14 = new javax.swing.JScrollPane();
        textArea14 = new javax.swing.JTextArea();
        respuesta15 = new javax.swing.JScrollPane();
        textArea15 = new javax.swing.JTextArea();
        tituloInterfaz = new javax.swing.JLabel();

        setBackground(new java.awt.Color(228, 251, 251));

        Siguiente.setBackground(new java.awt.Color(255, 204, 0));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(0, 0, 0));
        Siguiente.setText("Siguiente");
        Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        pregunta11.setBackground(new java.awt.Color(228, 251, 251));
        pregunta11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta11.setForeground(new java.awt.Color(0, 0, 0));
        pregunta11.setText("Pregunta #11 -----------------------------------");

        pregunta12.setBackground(new java.awt.Color(228, 251, 251));
        pregunta12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta12.setForeground(new java.awt.Color(0, 0, 0));
        pregunta12.setText("Pregunta #12 -----------------------------------");

        pregunta13.setBackground(new java.awt.Color(228, 251, 251));
        pregunta13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta13.setForeground(new java.awt.Color(0, 0, 0));
        pregunta13.setText("Pregunta #13 -----------------------------------");

        pregunta14.setBackground(new java.awt.Color(228, 251, 251));
        pregunta14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta14.setForeground(new java.awt.Color(0, 0, 0));
        pregunta14.setText("Pregunta #14 -----------------------------------");

        pregunta15.setBackground(new java.awt.Color(228, 251, 251));
        pregunta15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta15.setForeground(new java.awt.Color(0, 0, 0));
        pregunta15.setText("Pregunta #15 -----------------------------------");

        textArea11.setBackground(new java.awt.Color(228, 251, 251));
        textArea11.setColumns(20);
        textArea11.setForeground(new java.awt.Color(0, 0, 0));
        textArea11.setLineWrap(true);
        textArea11.setRows(5);
        textArea11.setWrapStyleWord(true);
        textArea11.setBorder(null);
        respuesta11.setViewportView(textArea11);

        textArea12.setBackground(new java.awt.Color(228, 251, 251));
        textArea12.setColumns(20);
        textArea12.setForeground(new java.awt.Color(0, 0, 0));
        textArea12.setLineWrap(true);
        textArea12.setRows(5);
        textArea12.setWrapStyleWord(true);
        textArea12.setBorder(null);
        respuesta12.setViewportView(textArea12);

        textArea13.setBackground(new java.awt.Color(228, 251, 251));
        textArea13.setColumns(20);
        textArea13.setForeground(new java.awt.Color(0, 0, 0));
        textArea13.setLineWrap(true);
        textArea13.setRows(5);
        textArea13.setWrapStyleWord(true);
        textArea13.setBorder(null);
        respuesta13.setViewportView(textArea13);

        textArea14.setBackground(new java.awt.Color(228, 251, 251));
        textArea14.setColumns(20);
        textArea14.setForeground(new java.awt.Color(0, 0, 0));
        textArea14.setLineWrap(true);
        textArea14.setRows(5);
        textArea14.setWrapStyleWord(true);
        textArea14.setBorder(null);
        respuesta14.setViewportView(textArea14);

        textArea15.setBackground(new java.awt.Color(228, 251, 251));
        textArea15.setColumns(20);
        textArea15.setForeground(new java.awt.Color(0, 0, 0));
        textArea15.setLineWrap(true);
        textArea15.setRows(5);
        textArea15.setWrapStyleWord(true);
        textArea15.setBorder(null);
        respuesta15.setViewportView(textArea15);

        tituloInterfaz.setBackground(new java.awt.Color(228, 251, 251));
        tituloInterfaz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tituloInterfaz.setForeground(new java.awt.Color(0, 0, 0));
        tituloInterfaz.setText("Preguntas presentadas en la prueba");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregunta11, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta11, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta12, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta12, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta13, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta13, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta14, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta14, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pregunta15, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respuesta15, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(tituloInterfaz))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tituloInterfaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pregunta11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuesta12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pregunta13)
                .addGap(18, 18, 18)
                .addComponent(respuesta13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(pregunta14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuesta14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Siguiente;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pregunta11;
    private javax.swing.JLabel pregunta12;
    private javax.swing.JLabel pregunta13;
    private javax.swing.JLabel pregunta14;
    private javax.swing.JLabel pregunta15;
    private javax.swing.JScrollPane respuesta11;
    private javax.swing.JScrollPane respuesta12;
    private javax.swing.JScrollPane respuesta13;
    private javax.swing.JScrollPane respuesta14;
    private javax.swing.JScrollPane respuesta15;
    private javax.swing.JTextArea textArea11;
    private javax.swing.JTextArea textArea12;
    private javax.swing.JTextArea textArea13;
    private javax.swing.JTextArea textArea14;
    private javax.swing.JTextArea textArea15;
    private javax.swing.JLabel tituloInterfaz;
    // End of variables declaration//GEN-END:variables
}
