/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author claud
 */
public class totalPreguntas4 extends javax.swing.JPanel {

    /**
     * Creates new form totalPreguntas4
     */
    public totalPreguntas4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Siguiente = new javax.swing.JButton();
        pregunta16 = new javax.swing.JLabel();
        pregunta17 = new javax.swing.JLabel();
        pregunta18 = new javax.swing.JLabel();
        pregunta19 = new javax.swing.JLabel();
        pregunta20 = new javax.swing.JLabel();
        respuesta16 = new javax.swing.JScrollPane();
        textArea16 = new javax.swing.JTextArea();
        respuesta17 = new javax.swing.JScrollPane();
        textArea17 = new javax.swing.JTextArea();
        respuesta18 = new javax.swing.JScrollPane();
        textArea18 = new javax.swing.JTextArea();
        respuesta19 = new javax.swing.JScrollPane();
        textArea19 = new javax.swing.JTextArea();
        respuesta20 = new javax.swing.JScrollPane();
        textArea20 = new javax.swing.JTextArea();
        TituloInterfaz = new javax.swing.JLabel();

        setBackground(new java.awt.Color(228, 251, 251));

        Siguiente.setBackground(new java.awt.Color(255, 204, 0));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(0, 0, 0));
        Siguiente.setText("Siguiente");
        Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        pregunta16.setBackground(new java.awt.Color(228, 251, 251));
        pregunta16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta16.setForeground(new java.awt.Color(0, 0, 0));
        pregunta16.setText("Pregunta #16 -----------------------------------");

        pregunta17.setBackground(new java.awt.Color(228, 251, 251));
        pregunta17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta17.setForeground(new java.awt.Color(0, 0, 0));
        pregunta17.setText("Pregunta #17 -----------------------------------");

        pregunta18.setBackground(new java.awt.Color(228, 251, 251));
        pregunta18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta18.setForeground(new java.awt.Color(0, 0, 0));
        pregunta18.setText("Pregunta #18 -----------------------------------");

        pregunta19.setBackground(new java.awt.Color(228, 251, 251));
        pregunta19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta19.setForeground(new java.awt.Color(0, 0, 0));
        pregunta19.setText("Pregunta #19 -----------------------------------");

        pregunta20.setBackground(new java.awt.Color(228, 251, 251));
        pregunta20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta20.setForeground(new java.awt.Color(0, 0, 0));
        pregunta20.setText("Pregunta #20 -----------------------------------");

        textArea16.setBackground(new java.awt.Color(228, 251, 251));
        textArea16.setColumns(20);
        textArea16.setForeground(new java.awt.Color(0, 0, 0));
        textArea16.setLineWrap(true);
        textArea16.setRows(5);
        textArea16.setWrapStyleWord(true);
        textArea16.setBorder(null);
        respuesta16.setViewportView(textArea16);

        textArea17.setBackground(new java.awt.Color(228, 251, 251));
        textArea17.setColumns(20);
        textArea17.setForeground(new java.awt.Color(0, 0, 0));
        textArea17.setLineWrap(true);
        textArea17.setRows(5);
        textArea17.setWrapStyleWord(true);
        textArea17.setBorder(null);
        respuesta17.setViewportView(textArea17);

        textArea18.setBackground(new java.awt.Color(228, 251, 251));
        textArea18.setColumns(20);
        textArea18.setForeground(new java.awt.Color(0, 0, 0));
        textArea18.setLineWrap(true);
        textArea18.setRows(5);
        textArea18.setWrapStyleWord(true);
        textArea18.setBorder(null);
        respuesta18.setViewportView(textArea18);

        respuesta19.setBackground(new java.awt.Color(228, 251, 251));
        respuesta19.setForeground(new java.awt.Color(0, 0, 0));

        textArea19.setBackground(new java.awt.Color(228, 251, 251));
        textArea19.setColumns(20);
        textArea19.setForeground(new java.awt.Color(0, 0, 0));
        textArea19.setLineWrap(true);
        textArea19.setRows(5);
        textArea19.setWrapStyleWord(true);
        textArea19.setBorder(null);
        respuesta19.setViewportView(textArea19);

        textArea20.setBackground(new java.awt.Color(228, 251, 251));
        textArea20.setColumns(20);
        textArea20.setForeground(new java.awt.Color(0, 0, 0));
        textArea20.setLineWrap(true);
        textArea20.setRows(5);
        textArea20.setWrapStyleWord(true);
        textArea20.setBorder(null);
        respuesta20.setViewportView(textArea20);

        TituloInterfaz.setBackground(new java.awt.Color(228, 251, 251));
        TituloInterfaz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloInterfaz.setForeground(new java.awt.Color(0, 0, 0));
        TituloInterfaz.setText("Preguntas presentadas en la prueba");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(TituloInterfaz))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(respuesta16, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta16, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta17, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuesta17, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta18, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuesta18, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta19, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuesta19, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pregunta20, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(respuesta20, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloInterfaz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuesta16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuesta17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta18)
                .addGap(18, 18, 18)
                .addComponent(respuesta18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(respuesta19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pregunta20)
                .addGap(18, 18, 18)
                .addComponent(respuesta20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel TituloInterfaz;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pregunta16;
    private javax.swing.JLabel pregunta17;
    private javax.swing.JLabel pregunta18;
    private javax.swing.JLabel pregunta19;
    private javax.swing.JLabel pregunta20;
    private javax.swing.JScrollPane respuesta16;
    private javax.swing.JScrollPane respuesta17;
    private javax.swing.JScrollPane respuesta18;
    private javax.swing.JScrollPane respuesta19;
    private javax.swing.JScrollPane respuesta20;
    private javax.swing.JTextArea textArea16;
    private javax.swing.JTextArea textArea17;
    private javax.swing.JTextArea textArea18;
    private javax.swing.JTextArea textArea19;
    private javax.swing.JTextArea textArea20;
    // End of variables declaration//GEN-END:variables
}
