/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author claud
 */
public class totalPreguntas5 extends javax.swing.JPanel {

    /**
     * Creates new form totalPreguntas5
     */
    public totalPreguntas5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPantalla = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        Siguiente = new javax.swing.JButton();
        pregunta1 = new javax.swing.JLabel();
        pregunta2 = new javax.swing.JLabel();
        pregunta3 = new javax.swing.JLabel();
        pregunta4 = new javax.swing.JLabel();
        pregunta5 = new javax.swing.JLabel();
        respuesta1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        respuesta2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();
        respuesta3 = new javax.swing.JScrollPane();
        textArea3 = new javax.swing.JTextArea();
        respuesta4 = new javax.swing.JScrollPane();
        textArea4 = new javax.swing.JTextArea();
        respuesta5 = new javax.swing.JScrollPane();
        textArea5 = new javax.swing.JTextArea();
        tituloInterfaz = new javax.swing.JLabel();

        fondoPantalla.setBackground(new java.awt.Color(227, 251, 251));
        fondoPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondoPantalla.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 470, 20));

        Siguiente.setBackground(new java.awt.Color(255, 204, 0));
        Siguiente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Siguiente.setForeground(new java.awt.Color(0, 0, 0));
        Siguiente.setText("Siguiente");
        Siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        fondoPantalla.add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 130, 40));

        pregunta1.setBackground(new java.awt.Color(228, 251, 251));
        pregunta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta1.setForeground(new java.awt.Color(0, 0, 0));
        pregunta1.setText("Pregunta #1 -----------------------------------");
        fondoPantalla.add(pregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 830, -1));

        pregunta2.setBackground(new java.awt.Color(228, 251, 251));
        pregunta2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta2.setForeground(new java.awt.Color(0, 0, 0));
        pregunta2.setText("Pregunta #2 -----------------------------------");
        fondoPantalla.add(pregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 830, -1));

        pregunta3.setBackground(new java.awt.Color(228, 251, 251));
        pregunta3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta3.setForeground(new java.awt.Color(0, 0, 0));
        pregunta3.setText("Pregunta #3 -----------------------------------");
        fondoPantalla.add(pregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 830, -1));

        pregunta4.setBackground(new java.awt.Color(228, 251, 251));
        pregunta4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta4.setForeground(new java.awt.Color(0, 0, 0));
        pregunta4.setText("Pregunta #4 -----------------------------------");
        fondoPantalla.add(pregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 830, 20));

        pregunta5.setBackground(new java.awt.Color(228, 251, 251));
        pregunta5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pregunta5.setForeground(new java.awt.Color(0, 0, 0));
        pregunta5.setText("Pregunta #5 -----------------------------------");
        fondoPantalla.add(pregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 830, -1));

        textArea1.setBackground(new java.awt.Color(228, 251, 251));
        textArea1.setColumns(20);
        textArea1.setForeground(new java.awt.Color(0, 0, 0));
        textArea1.setLineWrap(true);
        textArea1.setRows(5);
        textArea1.setWrapStyleWord(true);
        textArea1.setBorder(null);
        respuesta1.setViewportView(textArea1);

        fondoPantalla.add(respuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 840, 30));

        textArea2.setBackground(new java.awt.Color(228, 251, 251));
        textArea2.setColumns(20);
        textArea2.setForeground(new java.awt.Color(0, 0, 0));
        textArea2.setLineWrap(true);
        textArea2.setRows(5);
        textArea2.setWrapStyleWord(true);
        textArea2.setBorder(null);
        respuesta2.setViewportView(textArea2);

        fondoPantalla.add(respuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 840, 30));

        textArea3.setBackground(new java.awt.Color(228, 251, 251));
        textArea3.setColumns(20);
        textArea3.setForeground(new java.awt.Color(0, 0, 0));
        textArea3.setLineWrap(true);
        textArea3.setRows(5);
        textArea3.setWrapStyleWord(true);
        textArea3.setBorder(null);
        respuesta3.setViewportView(textArea3);

        fondoPantalla.add(respuesta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 840, 30));

        textArea4.setBackground(new java.awt.Color(228, 251, 251));
        textArea4.setColumns(20);
        textArea4.setForeground(new java.awt.Color(0, 0, 0));
        textArea4.setLineWrap(true);
        textArea4.setRows(5);
        textArea4.setWrapStyleWord(true);
        textArea4.setBorder(null);
        respuesta4.setViewportView(textArea4);

        fondoPantalla.add(respuesta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 840, 30));

        textArea5.setBackground(new java.awt.Color(228, 251, 251));
        textArea5.setColumns(20);
        textArea5.setForeground(new java.awt.Color(0, 0, 0));
        textArea5.setLineWrap(true);
        textArea5.setRows(5);
        textArea5.setWrapStyleWord(true);
        textArea5.setBorder(null);
        respuesta5.setViewportView(textArea5);

        fondoPantalla.add(respuesta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 840, 30));

        tituloInterfaz.setBackground(new java.awt.Color(228, 251, 251));
        tituloInterfaz.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tituloInterfaz.setForeground(new java.awt.Color(0, 0, 0));
        tituloInterfaz.setText("Preguntas presentadas en la prueba");
        fondoPantalla.add(tituloInterfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Siguiente;
    private javax.swing.JPanel fondoPantalla;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel pregunta1;
    private javax.swing.JLabel pregunta2;
    private javax.swing.JLabel pregunta3;
    private javax.swing.JLabel pregunta4;
    private javax.swing.JLabel pregunta5;
    private javax.swing.JScrollPane respuesta1;
    private javax.swing.JScrollPane respuesta2;
    private javax.swing.JScrollPane respuesta3;
    private javax.swing.JScrollPane respuesta4;
    private javax.swing.JScrollPane respuesta5;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextArea textArea2;
    private javax.swing.JTextArea textArea3;
    private javax.swing.JTextArea textArea4;
    private javax.swing.JTextArea textArea5;
    private javax.swing.JLabel tituloInterfaz;
    // End of variables declaration//GEN-END:variables
}
