/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.awt.Container;

/**
 *
 * @author claud
 */
public class VentanaPrincipal extends javax.swing.JPanel {
    
    /**
     * Creates new form ventanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IniciarSesion = new javax.swing.JLabel();
        NombreUsuario1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        IngresarCedula = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        PanelLogo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        IniciarSesion.setText("INICIAR SESIÓN");
        IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 40));

        NombreUsuario1.setBackground(new java.awt.Color(228, 251, 251));
        NombreUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NombreUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        NombreUsuario1.setText("Ingrese su nombre completo");
        NombreUsuario1.setBorder(null);
        NombreUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombreUsuario1MousePressed(evt);
            }
        });
        NombreUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreUsuario1ActionPerformed(evt);
            }
        });
        jPanel1.add(NombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 470, 30));

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 440, 20));

        Nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nombre.setText("NOMBRE");
        Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 440, 10));

        IngresarCedula.setBackground(new java.awt.Color(228, 251, 251));
        IngresarCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IngresarCedula.setForeground(new java.awt.Color(204, 204, 204));
        IngresarCedula.setText("Ingrese su cédula (V-)");
        IngresarCedula.setBorder(null);
        IngresarCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresarCedulaMousePressed(evt);
            }
        });
        IngresarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(IngresarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 470, 30));

        Cedula.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Cedula.setText("IDENTIFICACIÓN");
        Cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        PanelLogo.setBackground(new java.awt.Color(15, 192, 255));
        PanelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/holaaaaa.png"))); // NOI18N
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, 200));

        titulo1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        titulo1.setText("Generador de pruebas");
        titulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, 30));

        titulo2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        titulo2.setText("de programación");
        titulo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jPanel1.add(PanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 280, 470));

        aceptar.setBackground(new java.awt.Color(15, 192, 255));
        aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 110, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void NombreUsuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombreUsuario1MousePressed
        if (NombreUsuario1.getText().equals("Ingrese su nombre completo")){
            NombreUsuario1.setText("");
            NombreUsuario1.setForeground(Color.BLACK);
        }
        if (String.valueOf(IngresarCedula.getText()).isEmpty()){
            IngresarCedula.setText("Ingrese su cédula (V-)");
            IngresarCedula.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_NombreUsuario1MousePressed

    private void NombreUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreUsuario1ActionPerformed

    private void IngresarCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarCedulaMousePressed
        if(IngresarCedula.getText().equals("Ingrese su cédula (V-)")){
            IngresarCedula.setText("");
            IngresarCedula.setForeground(Color.BLACK);
        }

        if (String.valueOf(NombreUsuario1.getText()).isEmpty()){
            NombreUsuario1.setText("Ingrese su nombre completo");
            NombreUsuario1.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_IngresarCedulaMousePressed

    private void IngresarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngresarCedulaActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        SeleccionarLenguaje lenguaje = new SeleccionarLenguaje();
        lenguaje.setSize(880, 470);
        
        Container padre = this.getParent();
        
        padre.removeAll();
        padre.add(lenguaje);
        padre.revalidate();
        padre.repaint();
    }//GEN-LAST:event_aceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JTextField IngresarCedula;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JTextField NombreUsuario1;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JButton aceptar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
