/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import java.awt.Container;
import javax.swing.JOptionPane;
import modelos.Participante;

/**
 *
 * @author claud
 */
public class VentanaPrincipal extends javax.swing.JPanel {
    private PrincipalView cronometro;
    
    /**
     * Creates new form ventanaPrincipal
     * @param cronometro
     */
    public VentanaPrincipal(PrincipalView cronometro) {
        initComponents();
        this.cronometro = cronometro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        IniciarSesion = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Nombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ingresarCedula = new javax.swing.JTextField();
        Cedula = new javax.swing.JLabel();
        PanelLogo = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(228, 251, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        IniciarSesion.setText("INICIAR SESIÓN");
        IniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(IniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 40));

        nombreUsuario.setBackground(new java.awt.Color(228, 251, 251));
        nombreUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(204, 204, 204));
        nombreUsuario.setText("Ingrese su nombre completo");
        nombreUsuario.setBorder(null);
        nombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombreUsuarioMousePressed(evt);
            }
        });
        nombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 470, 30));

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 440, 20));

        Nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Nombre.setText("NOMBRE");
        Nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 440, 10));

        ingresarCedula.setBackground(new java.awt.Color(228, 251, 251));
        ingresarCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ingresarCedula.setForeground(new java.awt.Color(204, 204, 204));
        ingresarCedula.setText("Ingrese su cédula (V-)");
        ingresarCedula.setBorder(null);
        ingresarCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ingresarCedulaMousePressed(evt);
            }
        });
        ingresarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(ingresarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 470, 30));

        Cedula.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Cedula.setText("IDENTIFICACIÓN");
        Cedula.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        PanelLogo.setBackground(new java.awt.Color(15, 192, 255));
        PanelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/holaaaaa.png"))); // NOI18N
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, 200));

        titulo1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        titulo1.setText("Generador de pruebas");
        titulo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 240, 30));

        titulo2.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        titulo2.setText("de programación");
        titulo2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelLogo.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jPanel1.add(PanelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 280, 470));

        aceptar.setBackground(new java.awt.Color(15, 192, 255));
        aceptar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        aceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel1.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 110, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreUsuarioMousePressed
        if (nombreUsuario.getText().equals("Ingrese su nombre completo")){
            nombreUsuario.setText("");
            nombreUsuario.setForeground(Color.BLACK);
        }
        if (String.valueOf(ingresarCedula.getText()).isEmpty()){
            ingresarCedula.setText("Ingrese su cédula (V-)");
            ingresarCedula.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_nombreUsuarioMousePressed

    private void nombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreUsuarioActionPerformed

    private void ingresarCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarCedulaMousePressed
        if(ingresarCedula.getText().equals("Ingrese su cédula (V-)")){
            ingresarCedula.setText("");
            ingresarCedula.setForeground(Color.BLACK);
        }

        if (String.valueOf(nombreUsuario.getText()).isEmpty()){
            nombreUsuario.setText("Ingrese su nombre completo");
            nombreUsuario.setForeground(Color.GRAY);
        }

    }//GEN-LAST:event_ingresarCedulaMousePressed

    private void ingresarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresarCedulaActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if(ingresarCedula.getText().equals("Ingrese su cédula (V-)") || String.valueOf(nombreUsuario.getText()).isEmpty()){
            ShowAlert alerta = new ShowAlert("Error", "Ingrese su cedula", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(nombreUsuario.getText().equals("Ingrese su nombre completo") || String.valueOf(ingresarCedula.getText()).isEmpty()){
            ShowAlert alerta = new ShowAlert("Error", "Ingrese su nombre", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String cedula = ingresarCedula.getText();
        String nombre = nombreUsuario.getText();
        
        Participante participante = new Participante(nombre, cedula);
        
        SeleccionarLenguaje lenguaje = new SeleccionarLenguaje(participante, this.cronometro);
        lenguaje.setSize(880, 470);
        
        Container padre = this.getParent();
        
        padre.removeAll();
        padre.add(lenguaje);
        padre.revalidate();
        padre.repaint();
        
        cronometro.setContainer(padre);
        cronometro.setParticipante(participante);
    }//GEN-LAST:event_aceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Nombre;
    private javax.swing.JPanel PanelLogo;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField ingresarCedula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombreUsuario;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
